// TODO: Corrigir a numeração das subáreas, é para ser incremental, não deve repetir os números dos ids
module.exports = {
    areas: [
        {
            id: 1,
            nome: 'Ciências Exatas e da Terra',
            subareas: [
                { id: 1, nome: 'Matemática' },
                { id: 2, nome: 'Álgebra' },
                { id: 3, nome: 'Lógica Matemática' },
                { id: 4, nome: 'Teoria dos Números' },
                { id: 5, nome: 'Grupos de Álgebra Não-Comutativa' },
                { id: 6, nome: 'Álgebra Comutativa' },
                { id: 7, nome: 'Geometria Algébrica' },
                { id: 8, nome: 'Análise' },
                { id: 9, nome: 'Análise Complexa' },
                { id: 10, nome: 'Análise Funcional' },
                { id: 11, nome: 'Análise Funcional Não-Linear' },
                { id: 12, nome: 'Equações Diferenciais Ordinárias' },
                { id: 13, nome: 'Equações Diferenciais Parciais' },
                { id: 14, nome: 'Equações Diferenciais Funcionais' },
                { id: 15, nome: 'Geometria e Topologia' },
                { id: 16, nome: 'Geometria Diferencial' },
                { id: 17, nome: 'Topologia Algébrica' },
                { id: 18, nome: 'Topologia das Variedades' },
                { id: 19, nome: 'Sistemas Dinâmicos' },
                { id: 20, nome: 'Teoria das Singularidades e Teoria das Catástrofes' },
                { id: 21, nome: 'Teoria das Folheações' },
                { id: 22, nome: 'Matemática Aplicada' },
                { id: 23, nome: 'Física Matemática' },
                { id: 24, nome: 'Análise Numérica' },
                { id: 25, nome: 'Matemática Discreta e Combinatória' },
            ],
        },
        {
            id: 2,
            nome: 'Probabilidade e Estatística',
            subareas: [
                { id: 26, nome: 'Teoria Geral e Fundamentos da Probabilidade' },
                { id: 27, nome: 'Teoria Geral e Processos Estocásticos' },
                { id: 28, nome: 'Teoremas de Limite' },
                { id: 29, nome: 'Processos Markovianos' },
                { id: 30, nome: 'Análise Estocástica' },
                { id: 31, nome: 'Processos Estocásticos Especiais' },
                { id: 32, nome: 'Estatística' },
                { id: 33, nome: 'Fundamentos da Estatística' },
                { id: 34, nome: 'Inferência Paramétrica' },
                { id: 35, nome: 'Inferência Não-Paramétrica' },
                { id: 36, nome: 'Inferência em Processos Estocásticos' },
                { id: 37, nome: 'Análise Multivariada' },
                { id: 38, nome: 'Regressão e Correlação' },
                { id: 39, nome: 'Planejamento de Experimentos' },
                { id: 40, nome: 'Análise de Dados' },
            ],
        },
		{
            id: 3,
            nome: 'Ciência da Computação',
            subareas: [
                { id: 41, nome: 'Teoria da Computação' },
                { id: 42, nome: 'Computabilidade e Modelos de Computação' },
                { id: 43, nome: 'Linguagens Formais e Autômatos' },
                { id: 44, nome: 'Análise de Algoritmos e Complexidade de Computação' },
                { id: 45, nome: 'Lógicas e Semântica de Programas' },
                { id: 46, nome: 'Matemática da Computação' },
                { id: 47, nome: 'Matemática Simbólica e Modelos Analíticos e de Simulação' },
                { id: 48, nome: 'Metodologia e Técnicas da Computação' },
                { id: 49, nome: 'Linguagens de Programação' },
                { id: 50, nome: 'Engenharia de Software' },
                { id: 51, nome: 'Banco de Dados' },
                { id: 52, nome: 'Sistemas de Informação' },
                { id: 53, nome: 'Processamento Gráfico (Graphics)' },
                { id: 54, nome: 'Sistemas de Computação' },
                { id: 55, nome: 'Hardware' },
                { id: 56, nome: 'Arquitetura de Sistemas de Computação' },
                { id: 57, nome: 'Software Básico' },
                { id: 58, nome: 'Teleinformática' },
            ],
        },

		{
            id: 4,
            nome: 'Astronomia',
            subareas: [
                { id: 59, nome: 'Astronomia de Posição e Mecânica Celeste' },
                { id: 60, nome: 'Astronomia Fundamental' },
                { id: 61, nome: 'Astronomia Dinâmica' },
                { id: 62, nome: 'Astrofísica Estelar' },
                { id: 63, nome: 'Astrofísica do Meio Interestelar' },
                { id: 64, nome: 'Meio Interestelar' },
                { id: 65, nome: 'Nebulosa' },
                { id: 66, nome: 'Astrofísica Extragaláctica' },
                { id: 67, nome: 'Galáxias' },
                { id: 68, nome: 'Aglomerados de Galáxias' },
                { id: 69, nome: 'Quasares' },
                { id: 70, nome: 'Cosmologia' },
                { id: 71, nome: 'Astrofísica do Sistema Solar' },
                { id: 72, nome: 'Física Solar' },
                { id: 73, nome: 'Movimento da Terra' },
                { id: 74, nome: 'Sistema Planetário' },
                { id: 75, nome: 'Instrumentação Astronômica' },
                { id: 76, nome: 'Astronomia Ótica' },
                { id: 77, nome: 'Radioastronomia' },
                { id: 78, nome: 'Astronomia Espacial' },
                { id: 79, nome: 'Processamento de Dados Astronômicos' },
            ],
        },

		{
            id: 5,
            nome: 'Física',
            subareas: [
                { id: 80, nome: 'Física Geral' },
                { id: 81, nome: 'Métodos Matemáticos da Física' },
                { id: 82, nome: 'Física Clássica e Física Quântica; Mecânica e Campos' },
                { id: 83, nome: 'Relatividade e Gravitação' },
                { id: 84, nome: 'Física Estatística e Termodinâmica' },
                { id: 85, nome: 'Metrologia, Técnicas Gerais de Laboratório, Sistema de Instrumentação' },
                { id: 86, nome: 'Instrumentação Específica de Uso Geral em Física' },
                { id: 87, nome: 'Áreas Clássicas de Fenomenologia e suas Aplicações' },
                { id: 88, nome: 'Eletricidade e Magnetismo; Campos e Partículas Carregadas' },
                { id: 89, nome: 'Ótica' },
                { id: 90, nome: 'Acústica' },
                { id: 91, nome: 'Transferência de Calor; Processos Térmicos e Termodinâmicos' },
                { id: 92, nome: 'Mecânica, Elasticidade e Reologia' },
                { id: 93, nome: 'Dinâmica dos Fluidos' },
                { id: 94, nome: 'Física das Partículas Elementares e Campos' },
                { id: 95, nome: 'Teoria Geral de Partículas e Campos' },
                { id: 96, nome: 'Teorias Específicas e Modelos de Interação; Sistematica de Partículas; Raios Cósmicos' },
                { id: 97, nome: 'Reações Específicas e Fenomiologia de Partículas' },
                { id: 98, nome: 'Propriedades de Partículas Específicas e Ressonâncias' },
                { id: 99, nome: 'Física Nuclear' },
                { id: 100, nome: 'Estrutura Nuclear' },
                { id: 101, nome: 'Desintegração Nuclear e Radioatividade' },
                { id: 102, nome: 'Reações Nucleares e Espalhamento Geral' },
                { id: 103, nome: 'Reações Nucleares e Espalhamento (Reações Específicas)' },
                { id: 104, nome: 'Propriedades de Núcleos Específicos' },
                { id: 105, nome: 'Métodos Experimentais e Instrumentação para Partículas Elementares e Física Nuclear' },
                { id: 106, nome: 'Física Atômica e Molécular' },
                { id: 107, nome: 'Estrutura Eletrônica de Átomos e Moléculas; Teoria' },
                { id: 108, nome: 'Espectros Atômicos e Integração de Fótons' },
                { id: 109, nome: 'Espectros Moléculares e Interações de Fótons com Moléculas' },
                { id: 110, nome: 'Processos de Colisão e Interações de Átomos e Moléculas' },
                { id: 111, nome: 'Inf.Sobre Átomos e Moléculas Obtidos Experimentalmente;Instrumentação e Técnicas' },
                { id: 112, nome: 'Estudos de Átomos e Moléculas Especiais' },
                { id: 113, nome: 'Física dos Fluidos, Física de Plasmas e Descargas Elétricas' },
                { id: 114, nome: 'Cinética e Teoria de Transporte de Fluidos; Propriedades Físicas de Gases' },
                { id: 115, nome: 'Física de Plasmas e Descargas Elétricas' },
                { id: 116, nome: 'Física da Matéria Condensada' },
                { id: 117, nome: 'Estrutura de Líquidos e Sólidos; Cristalografia' },
                { id: 118, nome: 'Propriedades Mecânicas e Acústicas da Matéria Condensada' },
                { id: 119, nome: 'Dinâmica da Rede e Estatística de Cristais' },
                { id: 120, nome: 'Equação de Estado, Equilíbrio de Fases e Transições de Fase' },
                { id: 121, nome: 'Propriedades Térmicas da Matéria Condensada' },
                { id: 122, nome: 'Propriedades de Transportes de Matéria Condensada (Não Eletrônicas)' },
                { id: 123, nome: 'Campos Quânticos e Sólidos, Hélio, Líquido, Sólido' },
                { id: 124, nome: 'Superfícies e Interfaces; Películas e Filamentos' },
                { id: 125, nome: 'Estados Eletrônicos' },
                { id: 126, nome: 'Transp.Eletrônicos e Prop. Elétricas de Superfícies; Interfaces e Películas' },
                { id: 127, nome: 'Estruturas Eletrônicas e Propriedades Elétricas de Superfícies Interfaces e Películas' },
                { id: 128, nome: 'Supercondutividade' },
                { id: 129, nome: 'Materiais Magnéticos e Propriedades Magnéticas' },
                { id: 130, nome: 'Ressonância Mag.e Relax.Na Mat.Condens;Efeitos Mosbauer;Corr.Ang.Pertubada' },
                { id: 131, nome: 'Materiais Dielétricos e Propriedades Dielétricas' },
                { id: 132, nome: 'Prop.Óticas e Espectrosc.da Mat.Condens;Outras Inter.da Mat.Com Rad.e Part.' },
                { id: 133, nome: 'Emissão Eletrônica e Iônica por Líquidos e Sólidos; Fenômenos de Impacto' },
            ],
        },
		{
            id: 6,
            nome: 'Química',
            subareas: [
                { id: 134, nome: 'Química Orgânica' },
                { id: 135, nome: 'Estrutura, Conformação e Estereoquímica' },
                { id: 136, nome: 'Sintese Orgânica' },
                { id: 137, nome: 'Fisico-Química Orgânica' },
                { id: 138, nome: 'Fotoquímica Orgânica' },
                { id: 139, nome: 'Química dos Produtos Naturais' },
                { id: 140, nome: 'Evolução, Sistemática e Ecologia Química' },
                { id: 141, nome: 'Polimeros e Colóides' },
                { id: 142, nome: 'Química Inorgânica' },
                { id: 143, nome: 'Campos de Coordenação' },
                { id: 144, nome: 'Não-Metais e Seus Compostos' },
                { id: 145, nome: 'Compostos Organo-Metálicos' },
                { id: 146, nome: 'Determinação de Estrutura de Compostos Inorgânicos' },
                { id: 147, nome: 'Foto-Química Inorgânica' },
                { id: 148, nome: 'Fisico Química Inorgânica' },
                { id: 149, nome: 'Química Bio-Inorgânica' },
                { id: 150, nome: 'Fisico-Química' },
                { id: 151, nome: 'Cinética Química e Catálise' },
                { id: 152, nome: 'Eletroquímica' },
                { id: 153, nome: 'Espectroscopia' },
                { id: 154, nome: 'Química de Interfaces' },
                { id: 155, nome: 'Química do Estado Condensado' },
                { id: 156, nome: 'Química Nuclear e Radioquímica' },
                { id: 157, nome: 'Química Teórica' },
                { id: 158, nome: 'Termodinâmica Química' },
                { id: 159, nome: 'Química Analítica' },
                { id: 160, nome: 'Separação' },
                { id: 161, nome: 'Métodos Óticos de Análise' },
                { id: 162, nome: 'Eletroanalítica' },
                { id: 163, nome: 'Gravimetria' },
                { id: 164, nome: 'Titimetria' },
                { id: 165, nome: 'Instrumentação Analítica' },
                { id: 166, nome: 'Análise de Traços e Química Ambiental' },
            ],
        },
		{
            id: 7,
            nome: 'GeoCiências',
            subareas: [
                { id: 167, nome: 'Geologia' },
                { id: 168, nome: 'Mineralogia' },
                { id: 169, nome: 'Petrologia' },
                { id: 170, nome: 'Geoquímica' },
                { id: 171, nome: 'Geologia Regional' },
                { id: 172, nome: 'Geotectônica' },
                { id: 173, nome: 'Geocronologia' },
                { id: 174, nome: 'Cartografia Geológica' },
                { id: 175, nome: 'Metalogenia' },
                { id: 176, nome: 'Hidrogeologia' },
                { id: 177, nome: 'Prospecção Mineral' },
                { id: 178, nome: 'Sedimentologia' },
                { id: 179, nome: 'Paleontologia Estratigráfica' },
                { id: 180, nome: 'Estratigrafia' },
                { id: 181, nome: 'Geologia Ambiental' },
                { id: 182, nome: 'Geofísica' },
                { id: 183, nome: 'Geomagnetismo' },
                { id: 184, nome: 'Sismologia' },
                { id: 185, nome: 'Geotermia e Fluxo Térmico' },
                { id: 186, nome: 'Propriedades Físicas das Rochas' },
                { id: 187, nome: 'Geofísica Nuclear' },
                { id: 188, nome: 'Sensoriamento Remoto' },
                { id: 189, nome: 'Aeronomia' },
                { id: 190, nome: 'Desenvolvimento de Instrumentação Geofísica' },
                { id: 191, nome: 'Geofísica Aplicada' },
                { id: 192, nome: 'Gravimetria' },
                { id: 193, nome: 'Meteorologia' },
                { id: 194, nome: 'Meteorologia Dinâmica' },
                { id: 195, nome: 'Meteorologia Sinótica' },
                { id: 196, nome: 'Meteorologia Física' },
                { id: 197, nome: 'Química da Atmosfera' },
                { id: 198, nome: 'Instrumentação Meteorológica' },
                { id: 199, nome: 'Climatologia' },
                { id: 200, nome: 'Micrometeorologia' },
                { id: 201, nome: 'Sensoriamento Remoto da Atmosfera' },
                { id: 202, nome: 'Meteorologia Aplicada' },
                { id: 203, nome: 'Geodesia' },
                { id: 204, nome: 'Geodesia Física' },
                { id: 205, nome: 'Geodesia Geométrica' },
                { id: 206, nome: 'Geodesia Celeste' },
                { id: 207, nome: 'Fotogrametria' },
                { id: 208, nome: 'Cartografia Básica' },
                { id: 209, nome: 'Geografia Física' },
                { id: 210, nome: 'Geomorfologia' },
                { id: 211, nome: 'Climatologia Geográfica' },
                { id: 212, nome: 'Pedologia' },
                { id: 213, nome: 'Hidrogeografia' },
                { id: 214, nome: 'Geoecologia' },
                { id: 215, nome: 'Fotogeografia (Físico-Ecológica)' },
                { id: 216, nome: 'Geocartografia' },
            ],
        },
		{
            id: 8,
            nome: 'Oceanografia',
            subareas: [
                { id: 217, nome: 'Oceanografia Biológica' },
                { id: 218, nome: 'Interação entre os Organismos Marinhos e os Parâmetros Ambientais' },
                { id: 219, nome: 'Oceanografia Física' },
                { id: 220, nome: 'Variáveis Físicas da Água do Mar' },
                { id: 221, nome: 'Movimento da Água do Mar' },
                { id: 222, nome: 'Origem das Massas de Água' },
                { id: 223, nome: 'Interação do Oceano com o Leito do Mar' },
                { id: 224, nome: 'Interação do Oceano com a Atmosfera' },
                { id: 225, nome: 'Oceanografia Química' },
                { id: 226, nome: 'Propriedades Químicas da Água do Mar' },
                { id: 227, nome: 'Interações Químico-Biológicas/Geológicas das Substâncias Químicas da Água do Mar' },
                { id: 228, nome: 'Oceanografia Geológica' },
                { id: 229, nome: 'Geomorfologia Submarina' },
                { id: 230, nome: 'Sedimentologia Marinha' },
                { id: 231, nome: 'Geofísica Marinha' },
            ],
        },
		{
            id: 9,
            nome: 'Ciências Biológicas',
            subareas: [
                { id: 232, nome: 'Biologia Geral' },
                { id: 233, nome: 'Genética' },
                { id: 234, nome: 'Genética Quantitativa' },
                { id: 235, nome: 'Genética Molecular e de Microorganismos' },
                { id: 236, nome: 'Genética Vegetal' },
                { id: 237, nome: 'Genética Animal' },
                { id: 238, nome: 'Genética Humana e Médica' },
                { id: 239, nome: 'Mutagênese' },
                { id: 240, nome: 'Botânica' },
                { id: 241, nome: 'Paleobotânica' },
                { id: 242, nome: 'Morfologia Vegetal' },
                { id: 243, nome: 'Morfologia Externa' },
                { id: 244, nome: 'Citologia Vegetal' },
                { id: 245, nome: 'Anatomia Vegetal' },
                { id: 246, nome: 'Palinologia' },
                { id: 247, nome: 'Fisiologia Vegetal' },
                { id: 248, nome: 'Nutrição e Crescimento Vegetal' },
                { id: 249, nome: 'Reprodução Vegetal' },
                { id: 250, nome: 'Ecofisiologia Vegetal' },
                { id: 251, nome: 'Taxonomia Vegetal' },
                { id: 252, nome: 'Taxonomia de Criptógamos' },
                { id: 253, nome: 'Taxonomia de Fanerógamos' },
                { id: 254, nome: 'Fitogeografia' },
                { id: 255, nome: 'Botânica Aplicada' },
                { id: 256, nome: 'Zoologia' },
                { id: 257, nome: 'Paleozoologia' },
                { id: 258, nome: 'Morfologia dos Grupos Recentes' },
                { id: 259, nome: 'Fisiologia dos Grupos Recentes' },
                { id: 260, nome: 'Comportamento Animal' },
                { id: 261, nome: 'Taxonomia dos Grupos Recentes' },
                { id: 262, nome: 'Zoologia Aplicada' },
                { id: 263, nome: 'Conservação das Espécies Animais' },
                { id: 264, nome: 'Utilização dos Animais' },
                { id: 265, nome: 'Controle Populacional de Animais' },
                { id: 266, nome: 'Ecologia' },
                { id: 267, nome: 'Ecologia Teórica' },
                { id: 268, nome: 'Ecologia de Ecossistemas' },
                { id: 269, nome: 'Ecologia Aplicada' },
                { id: 270, nome: 'Morfologia' },
                { id: 271, nome: 'Citologia e Biologia Celular' },
                { id: 272, nome: 'Embriologia' },
                { id: 273, nome: 'Histologia' },
                { id: 274, nome: 'Anatomia' },
                { id: 275, nome: 'Anatomia Humana' },
                { id: 276, nome: 'Fisiologia' },
                { id: 277, nome: 'Fisiologia Geral' },
                { id: 278, nome: 'Fisiologia de Órgaos e Sistemas' },
                { id: 279, nome: 'Neurofisiologia' },
                { id: 280, nome: 'Fisiologia Cardiovascular' },
                { id: 281, nome: 'Fisiologia da Respiração' },
                { id: 282, nome: 'Fisiologia Renal' },
                { id: 283, nome: 'Fisiologia Endocrina' },
                { id: 284, nome: 'Fisiologia da Digestão' },
                { id: 285, nome: 'Cinesiologia' },
                { id: 286, nome: 'Fisiologia do Esforço' },
                { id: 287, nome: 'Fisiologia Comparada' },
                { id: 288, nome: 'Bioquímica' },
                { id: 289, nome: 'Química de Macromoléculas' },
                { id: 290, nome: 'Proteínas' },
                { id: 291, nome: 'Lipídeos' },
                { id: 292, nome: 'Glicídeos' },
                { id: 293, nome: 'Bioquímica dos Microorganismos' },
                { id: 294, nome: 'Metabolismo e Bioenergética' },
                { id: 295, nome: 'Biologia Molecular' },
                { id: 296, nome: 'Enzimologia' },
                { id: 297, nome: 'Biofísica' },
                { id: 298, nome: 'Biofísica Molecular' },
                { id: 299, nome: 'Biofísica Celular' },
                { id: 300, nome: 'Biofísica de Processos e Sistemas' },
                { id: 301, nome: 'Radiologia e Fotobiologia' },
                { id: 302, nome: 'Farmacologia' },
                { id: 303, nome: 'Farmacologia Geral' },
                { id: 304, nome: 'Farmacocinética' },
                { id: 305, nome: 'Biodisponibilidade' },
                { id: 306, nome: 'Farmacologia Autonômica' },
                { id: 307, nome: 'Neuropsicofarmacologia' },
                { id: 308, nome: 'Farmacologia Cardiorenal' },
                { id: 309, nome: 'Farmacologia Bioquímica e Molecular' },
                { id: 310, nome: 'Etnofarmacologia' },
                { id: 311, nome: 'Toxicologia' },
                { id: 312, nome: 'Farmacologia Clínica' },
                { id: 313, nome: 'Imunologia' },
                { id: 314, nome: 'Imunoquímica' },
                { id: 315, nome: 'Imunologia Celular' },
                { id: 316, nome: 'Imunogenética' },
                { id: 317, nome: 'Imunologia Aplicada' },
                { id: 318, nome: 'Microbiologia' },
                { id: 319, nome: 'Biologia e Fisiologia dos Microorganismos' },
                { id: 320, nome: 'Virologia' },
                { id: 321, nome: 'Bacteriologia' },
                { id: 322, nome: 'Micologia' },
                { id: 323, nome: 'Microbiologia Aplicada' },
                { id: 324, nome: 'Microbiologia Médica' },
                { id: 325, nome: 'Microbiologia Industrial e de Fermentação' },
                { id: 326, nome: 'Parasitologia' },
                { id: 327, nome: 'Protozoologia de Parasitos' },
                { id: 328, nome: 'Protozoologia Parasitária Humana' },
                { id: 329, nome: 'Protozoologia Parasitária Animal' },
                { id: 330, nome: 'Helmintologia de Parasitos' },
            ],
        },

		{
            id: 10,
            nome: 'Engenharias',
            subareas: [
				        { id: 331, nome: 'Engenharia Civil' },
                        { id: 332, nome: 'Construção Civil' },
                        { id: 333, nome: 'Materiais e Componentes de Construção' },
                        { id: 334, nome: 'Processos Construtivos' },
                        { id: 335, nome: 'Instalações Prediais' },
                        { id: 336, nome: 'Estruturas' },
                        { id: 337, nome: 'Estruturas de Concreto' },
                        { id: 338, nome: 'Estruturas de Madeiras' },
                        { id: 339, nome: 'Estruturas Metálicas' },
                        { id: 340, nome: 'Mecânica das Estruturas' },
                        { id: 341, nome: 'Geotécnica' },
                        { id: 342, nome: 'Fundações e Escavações' },
                        { id: 343, nome: 'Mecânicas das Rochas' },
                        { id: 344, nome: 'Mecânicas dos Solos' },
                        { id: 345, nome: 'Obras de Terra e Enrocamento' },
                        { id: 346, nome: 'Pavimentos' },
						{ id: 347, nome: 'Engenharia Hidráulica' },
						{ id: 348, nome: 'Hidráulica' },
						{ id: 349, nome: 'Hidrologia' },
						{ id: 350, nome: 'Infra-Estrutura de Transportes' },
						{ id: 351, nome: 'Aeroportos; Projeto e Construção' },
						{ id: 352, nome: 'Ferrovias; Projetos e Construção' },
						{ id: 353, nome: 'Portos e Vias Navegáveis; Projeto e Construção' },
						{ id: 354, nome: 'Rodovias; Projeto e Construção' },
						{ id: 355, nome: 'Engenharia de Minas' },
						{ id: 356, nome: 'Pesquisa Mineral' },
						{ id: 357, nome: 'Caracterização do Minério' },
						{ id: 358, nome: 'Dimensionamento de Jazidas' },
						{ id: 359, nome: 'Lavra' },
						{ id: 360, nome: 'Lavra a Céu Aberto' },
						{ id: 361, nome: 'Lavra de Mina Subterrânea' },
						{ id: 362, nome: 'Equipamentos de Lavra' },
						{ id: 363, nome: 'Tratamento de Minérios' },
						{ id: 364, nome: 'Métodos de Concentração e Enriquecimento de Minérios' },
						{ id: 365, nome: 'Equipamentos de Beneficiamento de Minérios' },
						{ id: 366, nome: 'Engenharia de Materiais e Metalúrgica' },
						{ id: 367, nome: 'Instalações e Equipamentos Metalúrgicos' },
						{ id: 368, nome: 'Metalurgia Extrativa' },
						{ id: 369, nome: 'Metalurgia de Transformação' },
						{ id: 370, nome: 'Metalurgia Física' },
						{ id: 371, nome: 'Engenharia Hidráulica' },
						{ id: 372, nome: 'Engenharia Elétrica' },
						{ id: 373, nome: 'Materiais Elétricos' },
						{ id: 374, nome: 'Materiais Condutores' },
						{ id: 375, nome: 'Materiais e Componentes Semicondutores' },
						{ id: 376, nome: 'Materiais e Dispositivos Supercondutores' },
						{ id: 377, nome: 'Materiais Dielétricos, Piezoelétricos e Ferroelétricos' },
						{ id: 378, nome: 'Materiais e Componentes Eletroóticos e Magnetoóticos, Materiais Fotoelétricos' },
						{ id: 379, nome: 'Materiais e Dispositivos Magnéticos' },
						{ id: 380, nome: 'Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação' },
						{ id: 381, nome: 'Medidas Elétricas' },
						{ id: 382, nome: 'Medidas Magnéticas' },
						{ id: 383, nome: 'Instrumentação Eletromecânica' },
						{ id: 384, nome: 'Instrumentação Eletrônica' },
						{ id: 385, nome: 'Sistemas Eletrônicos de Medida e de Controle' },
						{ id: 386, nome: 'Circuitos Elétricos, Magnéticos e Eletrônicos' },
						{ id: 387, nome: 'Teoria Geral dos Circuitos Elétricos' },
						{ id: 388, nome: 'Circuitos Lineares e Não-Lineares' },
						{ id: 389, nome: 'Circuitos Eletrônicos' },
						{ id: 390, nome: 'Circuitos Magnéticos, Magnetismos, Eletromagnetismo' },
						{ id: 391, nome: 'Sistemas Elétricos de Potência' },
						{ id: 392, nome: 'Geração da Energia Elétrica' },
						{ id: 393, nome: 'Transmissão da Energia Elétrica, Distribuição da Energia Elétrica' },
						{ id: 394, nome: 'Conversão e Retificação da Energia Elétrica' },
						{ id: 395, nome: 'Medição, Controle, Correção e Proteção de Sistemas Elétricos de Potência' },
						{ id: 396, nome: 'Máquinas Elétricas e Dispositivos de Potência' },
						{ id: 397, nome: 'Instalações Elétricas Prediais e Industriais' },
						{ id: 398, nome: 'Eletrônica Industrial, Sistemas e Controles Eletrônicos' },
						{ id: 399, nome: 'Eletrônica Industrial' },
						{ id: 400, nome: 'Automação Eletrônica de Processos Elétricos e Industriais' },
						{ id: 401, nome: 'Controle de Processos Eletrônicos, Retroalimentação' },
						{ id: 402, nome: 'Telecomunicações' },
						{ id: 403, nome: 'Teoria Eletromagnética, Microondas, Propagação de Ondas, Antenas' },
						{ id: 404, nome: 'Radionavegação e Radioastronomia' },
						{ id: 405, nome: 'Sistemas de Telecomunicações' },
						{ id: 406, nome: 'Engenharia Mecânica' },
						{ id: 407, nome: 'Fenômenos de Transporte' },
						{ id: 408, nome: 'Transferência de Calor' },
						{ id: 409, nome: 'Mecânica dos Fluidos' },
						{ id: 410, nome: 'Dinâmica dos Gases' },
						{ id: 411, nome: 'Princípios Variacionais e Métodos Numéricos' },
						{ id: 412, nome: 'Engenharia Térmica' },
						{ id: 413, nome: 'Termodinâmica' },
						{ id: 414, nome: 'Controle Ambiental' },
						{ id: 415, nome: 'Aproveitamento da Energia' },
						{ id: 416, nome: 'Mecânica dos Sólidos' },
						{ id: 417, nome: 'Mecânica dos Corpos Sólidos, Elásticos e Plásticos' },
						{ id: 418, nome: 'Dinâmica dos Corpos Rígidos, Elásticos e Plásticos' },
						{ id: 419, nome: 'Análise de Tensões' },
						{ id: 420, nome: 'Termoelasticidade' },
						{ id: 421, nome: 'Projetos de Máquinas' },
						{ id: 422, nome: 'Teoria dos Mecanismos' },
						{ id: 423, nome: 'Estática e Dinâmica Aplicada' },
						{ id: 424, nome: 'Elementos de Máquinas' },
						{ id: 425, nome: 'Fundamentos Gerais de Projetos das Máquinas' },
						{ id: 426, nome: 'Máquinas, Motores e Equipamentos' },
						{ id: 427, nome: 'Métodos de Síntese e Otimização Aplicados ao Projeto Mecânico' },
						{ id: 428, nome: 'Controle de Sistemas Mecânicos' },
						{ id: 429, nome: 'Aproveitamento de Energia' },
						{ id: 430, nome: 'Processos de Fabricação' },
						{ id: 431, nome: 'Matrizes e Ferramentas' },
						{ id: 432, nome: 'Máquinas de Usinagem e Conformação' },
						{ id: 433, nome: 'Controle Numérico' },
						{ id: 434, nome: 'Robotização' },
						{ id: 435, nome: 'Processos de Fabricação, Seleção Econômica' },
						{ id: 436, nome: 'Engenharia Química' },
						{ id: 437, nome: 'Processos Industriais de Engenharia Química' },
						{ id: 438, nome: 'Processos Bioquímicos' },
						{ id: 439, nome: 'Processos Orgânicos' },
						{ id: 440, nome: 'Processos Inorgânicos' },
						{ id: 441, nome: 'Operações Industriais e Equipamentos para Engenharia Química' },
						{ id: 442, nome: 'Reatores Químicos' },
						{ id: 443, nome: 'Operações Características de Processos Bioquímicos' },
						{ id: 444, nome: 'Operações de Separação e Mistura' },
						{ id: 445, nome: 'Tecnologia Química' },
						{ id: 446, nome: 'Balancos Globais de Matéria e Energia' },
						{ id: 447, nome: 'Água' },
						{ id: 448, nome: 'Álcool' },
						{ id: 449, nome: 'Alimentos' },
						{ id: 450, nome: 'Borrachas' },
						{ id: 451, nome: 'Carvão' },
						{ id: 452, nome: 'Cerâmica' },
						{ id: 453, nome: 'Cimento' },
						{ id: 454, nome: 'Couro' },
						{ id: 455, nome: 'Detergentes' },
						{ id: 456, nome: 'Fertilizantes' },
						{ id: 457, nome: 'Medicamentos' },
						{ id: 458, nome: 'Metais não-Ferrosos' },
						{ id: 459, nome: 'Óleos' },
						{ id: 460, nome: 'Papel e Celulose' },
						{ id: 461, nome: 'Petróleo e Petroquímica' },
						{ id: 462, nome: 'Polímeros' },
						{ id: 463, nome: 'Produtos Naturais' },
						{ id: 464, nome: 'Têxteis' },
						{ id: 465, nome: 'Tratamentos e Aproveitamento de Rejeitos' },
						{ id: 466, nome: 'Xisto' },
						{ id: 467, nome: 'Engenharia Sanitária' },
						{ id: 468, nome: 'Recursos Hídricos' },
						{ id: 469, nome: 'Planejamento Integrado dos Recursos Hídricos' },
						{ id: 470, nome: 'Tecnologia e Problemas Sanitários de Irrigação' },
						{ id: 471, nome: 'Águas Subterrâneas e Poços Profundos' },
						{ id: 472, nome: 'Controle de Enchentes e de Barragens' },
						{ id: 473, nome: 'Sedimentologia' },
						{ id: 474, nome: 'Tratamento de Águas de Abastecimento e Residuárias' },
						{ id: 475, nome: 'Química Sanitária' },
						{ id: 476, nome: 'Processos Simplificados de Tratamento de Águas' },
						{ id: 477, nome: 'Técnicas Convencionais de Tratamento de Águas' },
						{ id: 478, nome: 'Técnicas Avançadas de Tratamento de Águas' },
						{ id: 479, nome: 'Estudos e Caracterização de Efluentes Industriais' },
						{ id: 480, nome: 'Layout de Processos Industriais' },
						{ id: 481, nome: 'Resíduos Radioativos' },
						{ id: 482, nome: 'Saneamento Básico' },
						{ id: 483, nome: 'Técnicas de Abastecimento da Água' },
						{ id: 484, nome: 'Drenagem de Águas Residuárias' },
						{ id: 485, nome: 'Drenagem Urbana de Águas Pluviais' },
						{ id: 486, nome: 'Resíduos Sólidos, Domésticos e Industriais' },
						{ id: 487, nome: 'Limpeza Pública' },
						{ id: 488, nome: 'Instalações Hidráulico-Sanitárias' },
						{ id: 489, nome: 'Saneamento Ambiental' },
						{ id: 490, nome: 'Ecologia Aplicada à Engenharia Sanitária' },
						{ id: 491, nome: 'Microbiologia Aplicada e Engenharia Sanitária' },
						{ id: 492, nome: 'Parasitologia Aplicada à Engenharia Sanitária' },
						{ id: 493, nome: 'Qualidade do Ar, das Águas e do Solo' },
						{ id: 494, nome: 'Controle da Poluição' },
						{ id: 495, nome: 'Legislação Ambiental' },
						{ id: 496, nome: 'Engenharia de Produção' },
						{ id: 497, nome: 'Gerência de Produção' },
						{ id: 498, nome: 'Planejamento de Instalações Industriais' },
						{ id: 499, nome: 'Planejamento, Projeto e Controle de Sistemas de Produção' },
						{ id: 500, nome: 'Higiene e Segurança do Trabalho' },
						{ id: 501, nome: 'Suprimentos' },
						{ id: 502, nome: 'Garantia de Controle de Qualidade' },
						{ id: 503, nome: 'Pesquisa Operacional' },
						{ id: 504, nome: 'Processos Estocásticos e Teorias da Filas' },
						{ id: 505, nome: 'Programação Linear, Não-Linear, Mista e Dinâmica' },
						{ id: 506, nome: 'Séries Temporais' },
						{ id: 507, nome: 'Teoria dos Grafos' },
						{ id: 508, nome: 'Teoria dos Jogos' },
						{ id: 509, nome: 'Engenharia do Produto' },
						{ id: 510, nome: 'Ergonomia' },
						{ id: 511, nome: 'Metodologia de Projeto do Produto' },
						{ id: 512, nome: 'Processos de Trabalho' },
						{ id: 513, nome: 'Gerência do Projeto e do Produto' },
						{ id: 514, nome: 'Desenvolvimento de Produto' },
						{ id: 515, nome: 'Engenharia Econômica' },
						{ id: 516, nome: 'Estudo de Mercado' },
						{ id: 517, nome: 'Localização Industrial' },
						{ id: 518, nome: 'Análise de Custos' },
						{ id: 519, nome: 'Economia de Tecnologia' },
						{ id: 520, nome: 'Vida Econômica dos Equipamentos' },
						{ id: 521, nome: 'Avaliação de Projetos' },
						{ id: 522, nome: 'Engenharia Nuclear' },
						{ id: 523, nome: 'Aplicações de Radioisótopos' },
						{ id: 524, nome: 'Produção de Radioisótopos' },
						{ id: 525, nome: 'Aplicações Industriais de Radioisótopos' },
						{ id: 526, nome: 'Instrumentação para Medida e Controle de Radiação' },
						{ id: 527, nome: 'Fusão Controlada' },
						{ id: 528, nome: 'Processos Industriais da Fusão Controlada' },
						{ id: 529, nome: 'Problemas Tecnológicos da Fusão Controlada' },
						{ id: 530, nome: 'Combustível Nuclear' },
						{ id: 531, nome: 'Extração de Combustível Nuclear' },
						{ id: 532, nome: 'Conversão, Enriquecimento e Fabricação de Combustível Nuclear' },
						{ id: 533, nome: 'Reprocessamento de Combustível Nuclear' },
						{ id: 534, nome: 'Rejeitos de Combustível Nuclear' },
						{ id: 535, nome: 'Tecnologia dos Reatores' },
						{ id: 536, nome: 'Núcleo do Reator' },
						{ id: 537, nome: 'Materiais Nucleares e Blindagem de Reatores' },
						{ id: 538, nome: 'Transferência de Calor em Reatores' },
						{ id: 539, nome: 'Geração e Integração Com Sistemas Elétricos em Reatores' },
						{ id: 540, nome: 'Instrumentação Para Operação e Controle de Reatores' },
						{ id: 541, nome: 'Segurança, Localização e Licenciamento de Reatores' },
						{ id: 542, nome: 'Aspectos Econômicos de Reatores' },
						{ id: 543, nome: 'Engenharia de Transportes' },
						{ id: 544, nome: 'Planejamento de Transportes' },
						{ id: 545, nome: 'Planejamento e Organização do Sistema de Transporte' },
						{ id: 546, nome: 'Economia dos Transportes' },
						{ id: 547, nome: 'Veículos e Equipamentos de Controle' },
						{ id: 548, nome: 'Vias de Transporte' },
						{ id: 549, nome: 'Veículos de Transportes' },
						{ id: 550, nome: 'Estação de Transporte' },
						{ id: 551, nome: 'Equipamentos Auxiliares e Controles' },
						{ id: 552, nome: 'Operações de Transportes' },
						{ id: 553, nome: 'Engenharia de Tráfego' },
						{ id: 554, nome: 'Capacidade de Vias de Transporte' },
						{ id: 555, nome: 'Operação de Sistemas de Transporte' },
						{ id: 556, nome: 'Engenharia Naval e Oceânica' },
						{ id: 557, nome: 'Hidrodinâmica de Navios e Sistemas Oceânicos' },
						{ id: 558, nome: 'Resistência Hidrodinâmica' },
						{ id: 559, nome: 'Propulsão de Navios' },
						{ id: 560, nome: 'Estruturas Navais e Oceânicas' },
						{ id: 561, nome: 'Análise Teórica e Experimental de Estrutura' },
						{ id: 562, nome: 'Dinâmica Estrutural Naval e Oceânica' },
						{ id: 563, nome: 'Síntese Estrutural Naval e Oceânica' },
						{ id: 564, nome: 'Máquinas Marítimas' },
						{ id: 565, nome: 'Análise de Sistemas Propulsores' },
						{ id: 566, nome: 'Controle e Automação de Sistemas Propulsores' },
						{ id: 567, nome: 'Equipamentos Auxiliares do Sistema Propulsivo' },
						{ id: 568, nome: 'Motor de Propulsão' },
						{ id: 569, nome: 'Projeto de Navios e de Sistemas Oceânicos' },
						{ id: 570, nome: 'Projetos de Navios' },
						{ id: 571, nome: 'Projetos de Sistemas Oceânicos Fixos e Semi-Fixos' },
						{ id: 572, nome: 'Projetos de Embarcações Não-Convencionais' },
						{ id: 573, nome: 'Tecnologia de Construção Naval e de Sistemas Oceânicos' },
						{ id: 574, nome: 'Métodos de Fabricação de Navios e Sistemas Oceânicos' },
						{ id: 575, nome: 'Soldagem de Estruturas Navais e Oceânicos' },
						{ id: 576, nome: 'Custos de Construção Naval' },
						{ id: 577, nome: 'Normatização e Certificação de Qualidade de Navios' },
						{ id: 578, nome: 'Engenharia Aeroespacial' },
						{ id: 579, nome: 'Aerodinâmica' },
						{ id: 580, nome: 'Aerodinâmica de Aeronaves Espaciais' },
						{ id: 581, nome: 'Aerodinâmica dos Processos Geofísicos e Interplanetários' },
						{ id: 582, nome: 'Dinâmica de Voo' },
						{ id: 583, nome: 'Trajetórias e Órbitas' },
						{ id: 584, nome: 'Estabilidade e Controle' },
						{ id: 585, nome: 'Estruturas Aeroespaciais' },
						{ id: 586, nome: 'Aeroelasticidade' },
						{ id: 587, nome: 'Fadiga' },
						{ id: 588, nome: 'Projeto de Estruturas Aeroespaciais' },
						{ id: 589, nome: 'Materiais e Processos para Engenharia Aeronáutica e Aeroespacial' },
						{ id: 590, nome: 'Propulsão Aeroespacial' },
						{ id: 591, nome: 'Combustão e Escoamento com Reações Químicas' },
						{ id: 592, nome: 'Propulsão de Foguetes' },
						{ id: 593, nome: 'Máquinas de Fluxo' },
						{ id: 594, nome: 'Motores Altern nome:'},
						{ id: 595, nome: 'Sistemas Aeroespaciais' },
						{ id: 596, nome: 'Aviões' },
						{ id: 597, nome: 'Foguetes' },
						{ id: 598, nome: 'Helicópteros' },
						{ id: 599, nome: 'Hovercraft' },
						{ id: 600, nome: 'Satélites e Outros Dispositivos Aeroespaciais' },
						{ id: 601, nome: 'Normatização e Certificação de Qualidade de Aeronaves e Componentes' },
						{ id: 602, nome: 'Manutenção de Sistemas Aeroespaciais' },
						{ id: 603, nome: 'Engenharia Biomédica' },
						{ id: 604, nome: 'Bioengenharia' },
						{ id: 605, nome: 'Processamento de Sinais Biológicos' },
						{ id: 606, nome: 'Modelagem de Fenômenos Biológicos' },
						{ id: 607, nome: 'Modelagem de Sistemas Biológicos' },
						{ id: 608, nome: 'Engenharia Médica' },
						{ id: 609, nome: 'Biomateriais e Materiais Biocompatíveis' },
						{ id: 610, nome: 'Transdutores para Aplicações Biomédicas' },
						{ id: 611, nome: 'Instrumentação Odontológica e Médico-Hospitalar' },
						{ id: 612, nome: 'Tecnologia de Próteses' },
											
                
                // ... (outras subáreas de Engenharias)
            ],
        },

		{
			id: 11,
			nome: 'Ciências da Saúde',
			subareas: [
				
					    { id: 613, nome: 'Medicina' },
						{ id: 614, nome: 'Clínica Médica' },
						{ id: 615, nome: 'Angiologia' },
						{ id: 616, nome: 'Dermatologia' },
						{ id: 617, nome: 'Alergologia e Imunologia Clínica' },
						{ id: 618, nome: 'Cancerologia' },
						{ id: 619, nome: 'Hematologia' },
						{ id: 620, nome: 'Endocrinologia' },
						{ id: 621, nome: 'Neurologia' },
						{ id: 622, nome: 'Pediatria' },
						{ id: 623, nome: 'Doenças Infecciosas e Parasitárias' },
						{ id: 624, nome: 'Cardiologia' },
						{ id: 625, nome: 'Gastroenterologia' },
						{ id: 626, nome: 'Pneumologia' },
						{ id: 627, nome: 'Nefrologia' },
						{ id: 628, nome: 'Reumatologia' },
						{ id: 629, nome: 'Ginecologia e Obstetrícia' },
						{ id: 630, nome: 'Fisiatria' },
						{ id: 631, nome: 'Oftalmologia' },
						{ id: 632, nome: 'Ortopedia' },
						{ id: 633, nome: 'Cirurgia' },
						{ id: 634, nome: 'Cirurgia Plástica e Restauradora' },
						{ id: 635, nome: 'Cirurgia Otorrinolaringológica' },
						{ id: 636, nome: 'Cirurgia Oftalmológica' },
						{ id: 637, nome: 'Cirurgia Cardiovascular' },
						{ id: 638, nome: 'Cirurgia Torácica' },
						{ id: 639, nome: 'Cirurgia Gastroenterologia' },
						{ id: 640, nome: 'Cirurgia Pediátrica' },
						{ id: 641, nome: 'Neurocirurgia' },
						{ id: 642, nome: 'Cirurgia Urológica' },
						{ id: 643, nome: 'Cirurgia Proctológica' },
						{ id: 644, nome: 'Cirurgia Ortopédica' },
						{ id: 645, nome: 'Cirurgia Traumatológica' },
						{ id: 646, nome: 'Anestesiologia' },
						{ id: 647, nome: 'Cirurgia Experimental' },
						{ id: 648, nome: 'Saúde Materno-Infantil' },
						{ id: 649, nome: 'Psiquiatria' },
						{ id: 650, nome: 'Anatomia Patológica e Patologia Clínica' },
						{ id: 651, nome: 'Radiologia Médica' },
						{ id: 652, nome: 'Medicina Legal e Deontologia' },
						{ id: 653, nome: 'Odontologia' },
						{ id: 654, nome: 'Clínica Odontológica' },
						{ id: 655, nome: 'Cirurgia Buco-Maxilo-Facial' },
						{ id: 656, nome: 'Ortodontia' },
						{ id: 657, nome: 'Odontopediatria' },
						{ id: 658, nome: 'Periodontia' },
						{ id: 659, nome: 'Endodontia' },
						{ id: 660, nome: 'Radiologia Odontológica' },
						{ id: 661, nome: 'Odontologia Social e Preventiva' },
						{ id: 662, nome: 'Materiais Odontológicos' },
						{ id: 663, nome: 'Farmácia' },
						{ id: 664, nome: 'Farmacotecnia' },
						{ id: 665, nome: 'Farmacognosia' },
						{ id: 666, nome: 'Análise Toxicológica' },
						{ id: 667, nome: 'Análise e Controle e Medicamentos' },
						{ id: 668, nome: 'Bromatologia' },
						{ id: 669, nome: 'Enfermagem' },
						{ id: 670, nome: 'Enfermagem Médico-Cirúrgica' },
						{ id: 671, nome: 'Enfermagem Obstétrica' },
						{ id: 672, nome: 'Enfermagem Pediátrica' },
						{ id: 673, nome: 'Enfermagem Psiquiátrica' },
						{ id: 674, nome: 'Enfermagem de Doenças Contagiosas' },
						{ id: 675, nome: 'Enfermagem de Saúde Pública' },
						{ id: 676, nome: 'Nutrição' },
						{ id: 677, nome: 'Bioquímica da Nutrição' },
						{ id: 678, nome: 'Dietética' },
						{ id: 679, nome: 'Análise Nutricional de População' },
						{ id: 680, nome: 'Desnutrição e Desenvolvimento Fisiológico' },
						{ id: 681, nome: 'Saúde Coletiva' },
						{ id: 682, nome: 'Epidemiologia' },
						{ id: 683, nome: 'Saúde Pública' },
						{ id: 684, nome: 'Medicina Preventiva' },
						{ id: 685, nome: 'Fonoaudiologia' },
						{ id: 686, nome: 'Fisioterapia e Terapia Ocupacional' },
						{ id: 687, nome: 'Educação Física' },
					],
		},
		{
			id: 12,
			nome: 'Ciências Agrárias',
			subareas: [
				{ id: 688, nome: 'Agronomia' },
				{ id: 689, nome: 'Ciência do Solo' },
				{ id: 690, nome: 'Genese, Morfologia e Classificação dos Solos' },
				{ id: 691, nome: 'Física do Solo' },
				{ id: 692, nome: 'Química do Solo' },
				{ id: 693, nome: 'Microbiologia e Bioquímica do Solo' },
				{ id: 694, nome: 'Fertilidade do Solo e Adubação' },
				{ id: 695, nome: 'Manejo e Conservação do Solo' },
				{ id: 696, nome: 'Fitossanidade' },
				{ id: 697, nome: 'Fitopatologia' },
				{ id: 698, nome: 'Entomologia Agrícola' },
				{ id: 699, nome: 'Parasitologia Agrícola' },
				{ id: 700, nome: 'Microbiologia Agrícola' },
				{ id: 701, nome: 'Defesa Fitossanitária' },
				{ id: 702, nome: 'Fitotecnia' },
				{ id: 703, nome: 'Manejo e Tratos Culturais' },
				{ id: 704, nome: 'Mecanização Agrícola' },
				{ id: 705, nome: 'Produção e Beneficiamento de Sementes' },
				{ id: 706, nome: 'Produção de Mudas' },
				{ id: 707, nome: 'Melhoramento Vegetal' },
				{ id: 708, nome: 'Fisiologia de Plantas Cultivadas' },
				{ id: 709, nome: 'Matologia' },
				{ id: 710, nome: 'Floricultura, Parques e Jardins' },
				{ id: 711, nome: 'Floricultura' },
				{ id: 712, nome: 'Parques e Jardins' },
				{ id: 713, nome: 'Arborização de Vias Públicas' },
				{ id: 714, nome: 'Agrometeorologia' },
				{ id: 715, nome: 'Extensão Rural' },
				{ id: 716, nome: 'Recursos Florestais e Engenharia Florestal' },
				{ id: 717, nome: 'Silvicultura' },
				{ id: 718, nome: 'Dendrologia' },
				{ id: 719, nome: 'Florestamento e Reflorestamento' },
				{ id: 720, nome: 'Genética e Melhoramento Florestal' },
				{ id: 721, nome: 'Sementes Florestais' },
				{ id: 722, nome: 'Nutrição Florestal' },
				{ id: 723, nome: 'Fisiologia Florestal' },
				{ id: 724, nome: 'Solos Florestais' },
				{ id: 725, nome: 'Proteção Florestal' },
				{ id: 726, nome: 'Manejo Florestal' },
				{ id: 727, nome: 'Economia Florestal' },
				{ id: 728, nome: 'Politica e Legislação Florestal' },
				{ id: 729, nome: 'Administração Florestal' },
				{ id: 730, nome: 'Dendrometria e Inventário Florestal' },
				{ id: 731, nome: 'Fotointerpretação Florestal' },
				{ id: 732, nome: 'Ordenamento Florestal' },
				{ id: 733, nome: 'Técnicas e Operações Florestais' },
				{ id: 734, nome: 'Exploração Florestal' },
				{ id: 735, nome: 'Mecanização Florestal' },
				{ id: 736, nome: 'Tecnologia e Utilização de Produtos Florestais' },
				{ id: 737, nome: 'Anatomia e Identificação de Produtos Florestais' },
				{ id: 738, nome: 'Propriedades Físico-Mecânicas da Madeira' },
				{ id: 739, nome: 'Relações Água-Madeira e Secagem' },
				{ id: 740, nome: 'Tratamento da Madeira' },
				{ id: 741, nome: 'Processamento Mecânico da Madeira' },
				{ id: 742, nome: 'Química da Madeira' },
				{ id: 743, nome: 'Resinas de Madeiras' },
				{ id: 744, nome: 'Tecnologia de Celulose e Papel' },
				{ id: 745, nome: 'Tecnologia de Chapas' },
				{ id: 746, nome: 'Conservação da Natureza' },
				{ id: 747, nome: 'Hidrologia Florestal' },
				{ id: 748, nome: 'Conservação de Áreas Silvestres' },
				{ id: 749, nome: 'Conservação de Bacias Hidrográficas' },
				{ id: 750, nome: 'Recuperação de Áreas Degradadas' },
				{ id: 751, nome: 'Energia de Biomassa Florestal' },
				{ id: 752, nome: 'Engenharia Agrícola' },
				{ id: 753, nome: 'Máquinas e Implementos Agrícolas' },
				{ id: 754, nome: 'Engenharia de Água e Solo' },
				{ id: 755, nome: 'Irrigação e Drenagem' },
				{ id: 756, nome: 'Conservação de Solo e Água' },
				{ id: 757, nome: 'Engenharia de Processamento de Produtos Agrícolas' },
				{ id: 758, nome: 'Pré-Processamento de Produtos Agrícolas' },
				{ id: 759, nome: 'Armazenamento de Produtos Agrícolas' },
				{ id: 760, nome: 'Transferência de Produtos Agrícolas' },
				{ id: 761, nome: 'Construções Rurais e Ambiência' },
				{ id: 762, nome: 'Assentamento Rural' },
				{ id: 763, nome: 'Engenharia de Construções Rurais' },
				{ id: 764, nome: 'Saneamento Rural' },
				{ id: 765, nome: 'Energização Rural' },
				{ id: 766, nome: 'Zootecnia' },
				{ id: 767, nome: 'Ecologia dos Animais Domésticos e Etologia' },
				{ id: 768, nome: 'Genética e Melhoramento dos Animais Domésticos' },
				{ id: 769, nome: 'Nutrição e Alimentação Animal' },
				{ id: 770, nome: 'Exigências Nutricionais dos Animais' },
				{ id: 771, nome: 'Avaliação de Alimentos para Animais' },
				{ id: 772, nome: 'Conservação de Alimentos para Animais' },
				{ id: 773, nome: 'Pastagem e Forragicultura' },
				{ id: 774, nome: 'Avaliação, Produção e Conservação de Forragens' },
				{ id: 775, nome: 'Manejo e Conservação de Pastagens' },
				{ id: 776, nome: 'Fisiologia de Plantas Forrageiras' },
				{ id: 777, nome: 'Melhoramento de Plantas Forrageiras e Produção de Sementes' },
				{ id: 778, nome: 'Toxicologia e Plantas Tóxicas' },
				{ id: 779, nome: 'Produção Animal' },
				{ id: 780, nome: 'Criação de Animais' },
				{ id: 781, nome: 'Manejo de Animais' },
				{ id: 782, nome: 'Instalações para Produção Animal' },
				{ id: 783, nome: 'Medicina Veterinária' },
				{ id: 784, nome: 'Clínica e Cirurgia Animal' },
				{ id: 785, nome: 'Anestesiologia Animal' },
				{ id: 786, nome: 'Técnica Cirúrgica Animal' },
				{ id: 787, nome: 'Radiologia de Animais' },
				{ id: 788, nome: 'Farmacologia e Terapêutica Animal' },
				{ id: 789, nome: 'Obstetrícia Animal' },
				{ id: 790, nome: 'Clínica Veterinária' },
				{ id: 791, nome: 'Clínica Cirúrgica Animal' },
				{ id: 792, nome: 'Toxicologia Animal' },
				{ id: 793, nome: 'Medicina Veterinária Preventiva' },
				{ id: 794, nome: 'Epidemiologia Animal' },
				{ id: 795, nome: 'Saneamento Aplicado à Saúde do Homem' },
				{ id: 796, nome: 'Doenças Infecciosas de Animais' },
				{ id: 797, nome: 'Doenças Parasitárias de Animais' },
				{ id: 798, nome: 'Saúde Animal (Programas Sanitários)' },
				{ id: 799, nome: 'Patologia Animal' },
				{ id: 800, nome: 'Patologia Aviária' },
				{ id: 801, nome: 'Anatomia Patologia Animal' },
				{ id: 802, nome: 'Patologia Clínica Animal' },
				{ id: 803, nome: 'Reprodução Animal' },
				{ id: 804, nome: 'Ginecologia e Andrologia Animal' },
				{ id: 805, nome: 'Inseminação Artificial Animal' },
				{ id: 806, nome: 'Fisiopatologia da Reprodução Animal' },
				{ id: 807, nome: 'Inspeção de Produtos de Origem Animal' },
				{ id: 808, nome: 'Recursos Pesqueiros e Engenharia de Pesca' },
				{ id: 809, nome: 'Recursos Pesqueiros Marinhos' },
				{ id: 810, nome: 'Fatores Abióticos do Mar' },
				{ id: 811, nome: 'Avaliação de Estoques Pesqueiros Marinhos' },
				{ id: 812, nome: 'Exploração Pesqueira Marinha' },
				{ id: 813, nome: 'Manejo e Conservação de Recursos Pesqueiros Marinhos' },
				{ id: 814, nome: 'Recursos Pesqueiros de Águas Interiores' },
				{ id: 815, nome: 'Fatores Abióticos de Águas Interiores' },
				{ id: 816, nome: 'Avaliação de Estoques Pesqueiros de Águas Interiores' },
				{ id: 817, nome: 'Explotação Pesqueira de Águas Interiores' },
				{ id: 818, nome: 'Manejo e Conservação de Recursos Pesqueiros de Águas Interiores' },
				{ id: 819, nome: 'Aqüicultura' },
				{ id: 820, nome: 'Maricultura' },
				{ id: 821, nome: 'Carcinocultura' },
				{ id: 822, nome: 'Ostreicultura' },
				{ id: 823, nome: 'Piscicultura' },
				{ id: 824, nome: 'Engenharia de Pesca' },
				{ id: 825, nome: 'Ciência e Tecnologia de Alimentos' },
				{ id: 826, nome: 'Ciência de Alimentos' },
				{ id: 827, nome: 'Valor Nutritivo de Alimentos' },
				{ id: 828, nome: 'Química, Física, Físico-Química e Bioquímica dos Alim. e das Mat.-Primas Alimentares' },
				{ id: 829, nome: 'Microbiologia de Alimentos' },
				{ id: 830, nome: 'Fisiologia Pós-Colheita' },
				{ id: 831, nome: 'Toxicidade e Resíduos de Pesticidas em Alimentos' },
				{ id: 832, nome: 'Avaliação e Controle de Qualidade de Alimentos' },
				{ id: 833, nome: 'Padrões, Legislação e Fiscalização de Alimentos' },
				{ id: 834, nome: 'Tecnologia de Alimentos' },
				{ id: 835, nome: 'Tecnologia de Produtos de Origem Animal' },
				{ id: 836, nome: 'Tecnologia de Produtos de Origem Vegetal' },
				{ id: 837, nome: 'Tecnologia das Bebidas' },
				{ id: 838, nome: 'Tecnologia de Alimentos Dietéticos e Nutricionais' },
				{ id: 839, nome: 'Aproveitamento de Subprodutos' },
				{ id: 840, nome: 'Embalagens de Produtos Alimentares' },
				{ id: 841, nome: 'Engenharia de Alimentos' },
				{ id: 842, nome: 'Instalações Industriais de Produção de Alimentos' },
				{ id: 843, nome: 'Armazenamento de Alimentos' },
			],
		},

		{
            id: 13,
            nome: 'Ciências Sociais Aplicadas',
            subareas: [
                { id: 844, nome: 'Direito' },
				{ id: 845, nome: 'Teoria do Direito' },
				{ id: 846, nome: 'Teoria Geral do Direito' },
				{ id: 847, nome: 'Teoria Geral do Processo' },
				{ id: 848, nome: 'Teoria do Estado' },
				{ id: 849, nome: 'História do Direito' },
				{ id: 850, nome: 'Filosofia do Direito' },
				{ id: 851, nome: 'Lógica Jurídica' },
				{ id: 852, nome: 'Sociologia Jurídica' },
				{ id: 853, nome: 'Antropologia Jurídica' },
				{ id: 855, nome: 'Direito Público' },
				{ id: 856, nome: 'Direito Tributário' },
				{ id: 857, nome: 'Direito Penal' },
				{ id: 858, nome: 'Direito Processual Penal' },
				{ id: 859, nome: 'Direito Processual Civil' },
				{ id: 860, nome: 'Direito Constitucional' },
				{ id: 861, nome: 'Direito Administrativo' },
				{ id: 862, nome: 'Direito Internacional Público' },
				{ id: 863, nome: 'Direito Privado' },
				{ id: 864, nome: 'Direito Civil' },
				{ id: 865, nome: 'Direito Comercial' },
				{ id: 866, nome: 'Direito do Trabalho' },
				{ id: 867, nome: 'Direito Internacional Privado' },
				{ id: 868, nome: 'Direitos Especiais' },
				{ id: 869, nome: 'Administração' },
				{ id: 870, nome: 'Administração de Empresas' },
				{ id: 871, nome: 'Administração da Produção' },
				{ id: 872, nome: 'Administração Financeira' },
				{ id: 873, nome: 'Mercadologia' },
				{ id: 874, nome: 'Negócios Internacionais' },
				{ id: 875, nome: 'Administração de Recursos Humanos' },
				{ id: 876, nome: 'Administração Pública' },
				{ id: 877, nome: 'Contabilidade e Finanças Públicas' },
				{ id: 878, nome: 'Organizações Públicas' },
				{ id: 879, nome: 'Política e Planejamento Governamentais' },
				{ id: 880, nome: 'Administração de Pessoal' },
				{ id: 881, nome: 'Administração de Setores Específicos' },
				{ id: 882, nome: 'Ciências Contábeis' },
				{ id: 883, nome: 'Economia' },
				{ id: 884, nome: 'Teoria Econômica' },
				{ id: 885, nome: 'Economia Geral' },
				{ id: 886, nome: 'Teoria Geral da Economia' },
				{ id: 887, nome: 'História do Pensamento Econômico' },
				{ id: 888, nome: 'História Econômica' },
				{ id: 889, nome: 'Sistemas Econômicos' },
				{ id: 890, nome: 'Métodos Quantitativos em Economia' },
				{ id: 891, nome: 'Métodos e Modelos Matemáticos, Econométricos e Estatísticos' },
				{ id: 892, nome: 'Estatística Sócio-Econômica' },
				{ id: 893, nome: 'Contabilidade Nacional' },
				{ id: 894, nome: 'Economia Matemática' },
				{ id: 895, nome: 'Economia Monetária e Fiscal' },
				{ id: 896, nome: 'Teoria Monetária e Financeira' },
				{ id: 897, nome: 'Instituições Monetárias e Financeiras do Brasil' },
				{ id: 898, nome: 'Finanças Públicas Internas' },
				{ id: 899, nome: 'Política Fiscal do Brasil' },
				{ id: 900, nome: 'Crescimento, Flutuações e Planejamento Econômico' },
				{ id: 901, nome: 'Crescimento e Desenvolvimento Econômico' },
				{ id: 902, nome: 'Teoria e Política de Planejamento Econômico' },
				{ id: 903, nome: 'Flutuações Cíclicas e Projeções Econômicas' },
				{ id: 904, nome: 'Inflação' },
				{ id: 905, nome: 'Economia Internacional' },
				{ id: 906, nome: 'Teoria do Comércio Internacional' },
				{ id: 907, nome: 'Relações do Comércio; Política Comercial; Integração Econômica' },
				{ id: 908, nome: 'Balanço de Pagamentos; Finanças Internacionais' },
				{ id: 909, nome: 'Investimentos Internacionais e Ajuda Externa' },
				{ id: 910, nome: 'Economia dos Recursos Humanos' },
				{ id: 911, nome: 'Treinamento e Alocação de Mão-de-Obra; Oferta de Mão-de-Obra e Força de Trabalho' },
				{ id: 912, nome: 'Mercado de Trabalho; Política do Governo' },
				{ id: 913, nome: 'Sindicatos, Dissídios Coletivos, Relações de Emprego (Empregador/Empregado)' },
				{ id: 914, nome: 'Capital Humano' },
				{ id: 915, nome: 'Demografia Econômica' },
				{ id: 916, nome: 'Economia Industrial' },
				{ id: 917, nome: 'Organização Industrial e Estudos Industriais' },
				{ id: 918, nome: 'Mudança Tecnológica' },
				{ id: 919, nome: 'Economia do Bem-Estar Social' },
				{ id: 920, nome: 'Economia dos Programas de Bem-Estar Social' },
				{ id: 921, nome: 'Economia do Consumidor' },
				{ id: 922, nome: 'Economia Regional e Urbana' },
				{ id: 923, nome: 'Economia Regional' },
				{ id: 924, nome: 'Economia Urbana' },
				{ id: 925, nome: 'Renda e Tributação' },
				{ id: 926, nome: 'Economias Agrária e dos Recursos Naturais' },
				{ id: 927, nome: 'Economia Agrária' },
				{ id: 928, nome: 'Economia dos Recursos Naturais' },
				{ id: 929, nome: 'Arquitetura e Urbanismo' },
				{ id: 930, nome: 'Fundamentos de Arquitetura e Urbanismo' },
				{ id: 931, nome: 'História da Arquitetura e Urbanismo' },
				{ id: 932, nome: 'Teoria da Arquitetura' },
				{ id: 933, nome: 'História do Urbanismo' },
				{ id: 934, nome: 'Teoria do Urbanismo' },
				{ id: 935, nome: 'Projeto de Arquitetura e Urbanismo' },
				{ id: 936, nome: 'Planejamento e Projetos da Edificação' },
				{ id: 937, nome: 'Planejamento e Projeto do Espaço Urbano' },
				{ id: 938, nome: 'Planejamento e Projeto do Equipamento' },
				{ id: 939, nome: 'Tecnologia de Arquitetura e Urbanismo' },
				{ id: 940, nome: 'Adequação Ambiental' },
				{ id: 941, nome: 'Paisagismo' },
				{ id: 942, nome: 'Desenvolvimento Histórico do Paisagismo' },
				{ id: 943, nome: 'Conceituação de Paisagismo e Metodologia do Paisagismo' },
				{ id: 944, nome: 'Estudos de Organização do Espaço Exterior' },
				{ id: 945, nome: 'Projetos de Espaços Livres Urbanos' },
				{ id: 946, nome: 'Planejamento Urbano e Regional' },
				{ id: 947, nome: 'Fundamentos do Planejamento Urbano e Regional' },
				{ id: 948, nome: 'Teoria do Planejamento Urbano e Regional' },
				{ id: 949, nome: 'Teoria da Urbanização' },
				{ id: 950, nome: 'Política Urbana' },
				{ id: 951, nome: 'História Urbana' },
				{ id: 952, nome: 'Métodos e Técnicas do Planejamento Urbano e Regional' },
				{ id: 953, nome: 'Informação, Cadastro e Mapeamento' },
				{ id: 954, nome: 'Técnica de Previsão Urbana e Regional' },
				{ id: 955, nome: 'Técnicas de Análise e Avaliação Urbana e Regional' },
				{ id: 956, nome: 'Técnicas de Planejamento e Projeto Urbanos e Regionais' },
				{ id: 957, nome: 'Serviços Urbanos e Regionais' },
				{ id: 958, nome: 'Administração Municipal e Urbana' },
				{ id: 959, nome: 'Estudos da Habitação' },
				{ id: 960, nome: 'Aspectos Sociais do Planejamento Urbano e Regional' },
				{ id: 961, nome: 'Aspectos Econômicos do Planejamento Urbano e Regional' },
				{ id: 962, nome: 'Aspectos Físico-Ambientais do Planejamento Urbano e Regional' },
				{ id: 963, nome: 'Serviços Comunitários' },
				{ id: 964, nome: 'Infraestruturas Urbanas e Regionais' },
				{ id: 965, nome: 'Transporte e Tráfego Urbano e Regional' },
				{ id: 966, nome: 'Legislação Urbana e Regional' },
				{ id: 967, nome: 'Demografia' },
				{ id: 968, nome: 'Distribuição Espacial' },
				{ id: 969, nome: 'Distribuição Espacial Geral' },
				{ id: 970, nome: 'Distribuição Espacial Urbana' },
				{ id: 971, nome: 'Distribuição Espacial Rural' },
				{ id: 972, nome: 'Tendência Populacional' },
				{ id: 973, nome: 'Tendências Passadas' },
				{ id: 974, nome: 'Taxas e Estimativas Correntes' },
				{ id: 975, nome: 'Projeções' },
				{ id: 976, nome: 'Componentes da Dinâmica Demográfica' },
				{ id: 977, nome: 'Fecundidade' },
				{ id: 978, nome: 'Mortalidade' },
				{ id: 979, nome: 'Migração' },
				{ id: 980, nome: 'Nupcialidade e Família' },
				{ id: 981, nome: 'Casamento e Divórcio' },
				{ id: 982, nome: 'Família e Reprodução' },
				{ id: 983, nome: 'Demografia Histórica' },
				{ id: 984, nome: 'Distribuição Espacial' },
				{ id: 985, nome: 'Natalidade, Mortalidade, Migração' },
				{ id: 986, nome: 'Nupcialidade e Família' },
				{ id: 987, nome: 'Métodos e Técnicas de Demografia Histórica' },
				{ id: 988, nome: 'Política Pública e População' },
				{ id: 989, nome: 'Política Populacional' },
				{ id: 990, nome: 'Políticas de Redistribuição de População' },
				{ id: 991, nome: 'Políticas de Planejamento Familiar' },
				{ id: 992, nome: 'Fontes de Dados Demográficos' },
				{ id: 993, nome: 'Ciência da Informação' },
				{ id: 994, nome: 'Teoria da Informação' },
				{ id: 995, nome: 'Teoria Geral da Informação' },
				{ id: 996, nome: 'Processos da Comunicação' },
				{ id: 997, nome: 'Representação da Informação' },
				{ id: 998, nome: 'Biblioteconomia' },
				{ id: 999, nome: 'Teoria da Classificação' },
				{ id: 1000, nome: 'Métodos Quantitativos. Bibliometria' },
				{ id: 1001, nome: 'Técnicas de Recuperação de Informação' },
				{ id: 1002, nome: 'Processos de Disseminação da Informação' },
				{ id: 1003, nome: 'Arquivologia' },
				{ id: 1004, nome: 'Organização de Arquivos' },
				{ id: 1005, nome: 'Museologia' },
				{ id: 1006, nome: 'Comunicação' },
				{ id: 1007, nome: 'Teoria da Comunicação' },
				{ id: 1008, nome: 'Jornalismo e Editoração' },
				{ id: 1009, nome: 'Teoria e Ética do Jornalismo' },
				{ id: 1010, nome: 'Organização Editorial de Jornais' },
				{ id: 1011, nome: 'Organização Comercial de Jornais' },
				{ id: 1012, nome: 'Jornalismo Especializado (Comunitário, Rural, Empresarial, Científico)' },
				{ id: 1013, nome: 'Rádio e Televisão' },
				{ id: 1014, nome: 'Radiodifusão' },
				{ id: 1015, nome: 'Videodifusão' },
				{ id: 1016, nome: 'Relações Públicas e Propaganda' },
				{ id: 1017, nome: 'Comunicação Visual' },
				{ id: 1018, nome: 'Serviço Social' },
				{ id: 1019, nome: 'Fundamentos do Serviço Social' },
				{ id: 1020, nome: 'Serviço Social Aplicado' },
				{ id: 1021, nome: 'Serviço Social do Trabalho' },
				{ id: 1022, nome: 'Serviço Social da Educação' },
				{ id: 1023, nome: 'Serviço Social do Menor' },
				{ id: 1024, nome: 'Serviço Social da Saúde' },
				{ id: 1025, nome: 'Serviço Social da Habitação' },
				{ id: 1026, nome: 'Economia Doméstica' },
				{ id: 1027, nome: 'Desenho Industrial' },
				{ id: 1028, nome: 'Programação Visual' },
				{ id: 1029, nome: 'Desenho de Produto' },
				{ id: 1030, nome: 'Turismo' },
            ],
        },


		{
            id: 14,
            nome: 'Ciências Humanas',
            subareas: [
                { id: 1031, nome: 'Filosofia' },
				{ id: 1032, nome: 'História da Filosofia' },
				{ id: 1033, nome: 'Metafísica' },
				{ id: 1034, nome: 'Lógica' },
				{ id: 1035, nome: 'Ética' },
				{ id: 1036, nome: 'Epistemologia' },
				{ id: 1037, nome: 'Filosofia Brasileira' },
				{ id: 1038, nome: 'Sociologia' },
				{ id: 1039, nome: 'Fundamentos da Sociologia' },
				{ id: 1040, nome: 'Teoria Sociológica' },
				{ id: 1041, nome: 'História da Sociologia' },
				{ id: 1042, nome: 'Sociologia do Conhecimento' },
				{ id: 1043, nome: 'Sociologia do Desenvolvimento' },
				{ id: 1044, nome: 'Sociologia Urbana' },
				{ id: 1045, nome: 'Sociologia Rural' },
				{ id: 1046, nome: 'Sociologia da Saúde' },
				{ id: 1047, nome: 'Outras Sociologias Específicas' },
				{ id: 1048, nome: 'Antropologia' },
				{ id: 1049, nome: 'Teoria Antropológica' },
				{ id: 1050, nome: 'Etnologia Indígena' },
				{ id: 1051, nome: 'Antropologia Urbana' },
				{ id: 1052, nome: 'Antropologia Rural' },
				{ id: 1053, nome: 'Antropologia das Populações Afro-Brasileiras' },
				{ id: 1054, nome: 'Arqueologia' },
				{ id: 1055, nome: 'Teoria e Método em Arqueologia' },
				{ id: 1056, nome: 'Arqueologia Pré-Histórica' },
				{ id: 1057, nome: 'Arqueologia Histórica' },
				{ id: 1058, nome: 'História' },
				{ id: 1059, nome: 'Teoria e Filosofia da História' },
				{ id: 1060, nome: 'História Antiga e Medieval' },
				{ id: 1061, nome: 'História Moderna e Contemporânea' },
				{ id: 1062, nome: 'História da América' },
				{ id: 1063, nome: 'História dos Estados Unidos' },
				{ id: 1064, nome: 'História Latino-Americana' },
				{ id: 1065, nome: 'História do Brasil' },
				{ id: 1066, nome: 'História do Brasil Colônia' },
				{ id: 1067, nome: 'História do Brasil Império' },
				{ id: 1068, nome: 'História do Brasil República' },
				{ id: 1069, nome: 'História Regional do Brasil' },
				{ id: 1070, nome: 'História das Ciências' },
				{ id: 1071, nome: 'Geografia' },
				{ id: 1072, nome: 'Geografia Humana' },
				{ id: 1073, nome: 'Geografia da População' },
				{ id: 1074, nome: 'Geografia Agrária' },
				{ id: 1075, nome: 'Geografia Urbana' },
				{ id: 1076, nome: 'Geografia Econômica' },
				{ id: 1077, nome: 'Geografia Política' },
				{ id: 1078, nome: 'Geografia Regional' },
				{ id: 1079, nome: 'Teoria do Desenvolvimento Regional' },
				{ id: 1080, nome: 'Regionalização' },
				{ id: 1081, nome: 'Análise Regional' },
				{ id: 1082, nome: 'Psicologia' },
				{ id: 1083, nome: 'Fundamentos e Medidas da Psicologia' },
				{ id: 1084, nome: 'História, Teorias e Sistemas em Psicologia' },
				{ id: 1085, nome: 'Metodologia, Instrumentação e Equipamento em Psicologia' },
				{ id: 1086, nome: 'Construção e Validade de Testes, Escalas e Outras Medidas Psicológicas' },
				{ id: 1087, nome: 'Técnicas de Processamento Estatístico, Matemático e Computacional em Psicologia' },
				{ id: 1088, nome: 'Psicologia Experimental' },
				{ id: 1089, nome: 'Processos Perceptuais e Motores' },
				{ id: 1090, nome: 'Processos de Aprendizagem, Memória e Motivação' },
				{ id: 1091, nome: 'Processos Cognitivos e Atencionais' },
				{ id: 1092, nome: 'Estados Subjetivos e Emoção' },
				{ id: 1093, nome: 'Psicologia Fisiológica' },
				{ id: 1094, nome: 'Neurologia, Eletrofisiologia e Comportamento' },
				{ id: 1095, nome: 'Processos Psico-Fisiológicos' },
				{ id: 1096, nome: 'Estimulação Elétrica e com Drogas; Comportamento' },
				{ id: 1097, nome: 'Psicobiologia' },
				{ id: 1098, nome: 'Psicologia Comparativa' },
				{ id: 1099, nome: 'Estudos Naturalísticos do Comportamento Animal' },
				{ id: 1100, nome: 'Mecanismos Instintivos e Processos Sociais em Animais' },
				{ id: 1101, nome: 'Psicologia Social' },
				{ id: 1102, nome: 'Relações Interpessoais' },
				{ id: 1103, nome: 'Processos Grupais e de Comunicação' },
				{ id: 1104, nome: 'Papéis e Estruturas Sociais; Indivíduo' },
				{ id: 1105, nome: 'Psicologia Cognitiva' },
				{ id: 1106, nome: 'Psicologia do Desenvolvimento Humano' },
				{ id: 1107, nome: 'Processos Perceptuais e Cognitivos; Desenvolvimento' },
				{ id: 1108, nome: 'Desenvolvimento Social e da Personalidade' },
				{ id: 1109, nome: 'Psicologia do Ensino e da Aprendizagem' },
				{ id: 1110, nome: 'Planejamento Institucional' },
				{ id: 1111, nome: 'Programação de Condições de Ensino' },
				{ id: 1112, nome: 'Treinamento de Pessoal' },
				{ id: 1113, nome: 'Aprendizagem e Desempenho Acadêmicos' },
				{ id: 1114, nome: 'Ensino e Aprendizagem na Sala de Aula' },
				{ id: 1115, nome: 'Psicologia do Trabalho e Organizacional' },
				{ id: 1116, nome: 'Análise Institucional' },
				{ id: 1117, nome: 'Recrutamento e Seleção de Pessoal' },
				{ id: 1118, nome: 'Treinamento e Avaliação' },
				{ id: 1119, nome: 'Fatores Humanos no Trabalho' },
				{ id: 1120, nome: 'Planejamento Ambiental e Comportamento Humano' },
				{ id: 1121, nome: 'Tratamento e Prevenção Psicológica' },
				{ id: 1122, nome: 'Intervenção Terapêutica' },
				{ id: 1123, nome: 'Programas de Atendimento Comunitário' },
				{ id: 1124, nome: 'Treinamento e Reabilitação' },
				{ id: 1125, nome: 'Desvios da Conduta' },
				{ id: 1126, nome: 'Distúrbios da Linguagem' },
				{ id: 1127, nome: 'Distúrbios Psicossomáticos' },
				{ id: 1128, nome: 'Educação' },
				{ id: 1129, nome: 'Fundamentos da Educação' },
				{ id: 1130, nome: 'Filosofia da Educação' },
				{ id: 1131, nome: 'História da Educação' },
				{ id: 1132, nome: 'Sociologia da Educação' },
				{ id: 1133, nome: 'Antropologia Educacional' },
				{ id: 1134, nome: 'Economia da Educação' },
				{ id: 1135, nome: 'Psicologia Educacional' },
				{ id: 1136, nome: 'Administração Educacional' },
				{ id: 1137, nome: 'Administração de Sistemas Educacionais' },
				{ id: 1138, nome: 'Administração de Unidades Educativas' },
				{ id: 1139, nome: 'Planejamento e Avaliação Educacional' },
				{ id: 1140, nome: 'Política Educacional' },
				{ id: 1141, nome: 'Planejamento Educacional' },
				{ id: 1142, nome: 'Avaliação de Sistemas, Instituições, Planos e Programas Educacionais' },
				{ id: 1143, nome: 'Ensino-Aprendizagem' },
				{ id: 1144, nome: 'Teorias da Instrução' },
				{ id: 1145, nome: 'Métodos e Técnicas de Ensino' },
				{ id: 1146, nome: 'Tecnologia Educacional' },
				{ id: 1147, nome: 'Avaliação da Aprendizagem' },
				{ id: 1148, nome: 'Currículo' },
				{ id: 1149, nome: 'Teoria Geral de Planejamento e Desenvolvimento Curricular' },
				{ id: 1150, nome: 'Currículos Específicos para Níveis e Tipos de Educação' },
				{ id: 1151, nome: 'Orientação e Aconselhamento' },
				{ id: 1152, nome: 'Orientação Educacional' },
				{ id: 1153, nome: 'Orientação Vocacional' },
				{ id: 1154, nome: 'Tópicos Específicos de Educação' },
				{ id: 1155, nome: 'Educação de Adultos' },
				{ id: 1156, nome: 'Educação Permanente' },
				{ id: 1157, nome: 'Educação Rural' },
				{ id: 1158, nome: 'Educação em Periferias Urbanas' },
				{ id: 1159, nome: 'Educação Especial' },
				{ id: 1160, nome: 'Educação Pré-Escolar' },
				{ id: 1161, nome: 'Ensino Profissionalizante' },
				{ id: 1162, nome: 'Ciência Política' },
				{ id: 1163, nome: 'Teoria Política' },
				{ id: 1164, nome: 'Teoria Política Clássica' },
				{ id: 1165, nome: 'Teoria Política Medieval' },
				{ id: 1166, nome: 'Teoria Política Moderna' },
				{ id: 1167, nome: 'Teoria Política Contemporânea' },
				{ id: 1168, nome: 'Estado e Governo' },
				{ id: 1169, nome: 'Estrutura e Transformação do Estado' },
				{ id: 1170, nome: 'Sistemas Governamentais Comparados' },
				{ id: 1171, nome: 'Relações Intergovernamentais' },
				{ id: 1172, nome: 'Estudos do Poder Local' },
				{ id: 1173, nome: 'Instituições Governamentais Específicas' },
				{ id: 1174, nome: 'Comportamento Político' },
				{ id: 1175, nome: 'Estudos Eleitorais e Partidos Políticos' },
				{ id: 1176, nome: 'Atitude e Ideologias Políticas' },
				{ id: 1177, nome: 'Conflitos e Coalizões Políticas' },
				{ id: 1178, nome: 'Comportamento Legislativo' },
				{ id: 1179, nome: 'Classes Sociais e Grupos de Interesse' },
				{ id: 1180, nome: 'Políticas Públicas' },
				{ id: 1181, nome: 'Análise do Processo Decisório' },
				{ id: 1182, nome: 'Análise Institucional' },
				{ id: 1183, nome: 'Técnicas de Antecipação' },
				{ id: 1184, nome: 'Política Internacional' },
				{ id: 1185, nome: 'Política Externa do Brasil' },
				{ id: 1186, nome: 'Organizações Internacionais' },
				{ id: 1187, nome: 'Integração Internacional, Conflito, Guerra e Paz' },
				{ id: 1188, nome: 'Relações Internacionais, Bilaterais e Multilaterais' },
				{ id: 1189, nome: 'Teologia' },
				{ id: 1190, nome: 'História da Teologia' },
				{ id: 1191, nome: 'Teologia Moral' },
				{ id: 1192, nome: 'Teologia Sistemática' },
				{ id: 1193, nome: 'Teologia Pastoral' },
            ],
        },

		{
            id: 15,
            nome: 'Lingüística, Letras e Artes ',
            subareas: [
				{ id: 1194, nome: 'Linguística' },
				{ id: 1195, nome: 'Teoria e Análise Linguística' },
				{ id: 1196, nome: 'Fisiologia da Linguagem' },
				{ id: 1197, nome: 'Linguística Histórica' },
				{ id: 1198, nome: 'Sociolinguística e Dialetologia' },
				{ id: 1199, nome: 'Psicolinguística' },
				{ id: 1200, nome: 'Linguística Aplicada' },
				{ id: 1201, nome: 'Letras' },
				{ id: 1202, nome: 'Língua Portuguesa' },
				{ id: 1203, nome: 'Línguas Estrangeiras Modernas' },
				{ id: 1204, nome: 'Línguas Clássicas' },
				{ id: 1205, nome: 'Línguas Indígenas' },
				{ id: 1206, nome: 'Teoria Literária' },
				{ id: 1207, nome: 'Literatura Brasileira' },
				{ id: 1208, nome: 'Outras Literaturas Vernáculas' },
				{ id: 1209, nome: 'Literaturas Estrangeiras Modernas' },
				{ id: 1210, nome: 'Literaturas Clássicas' },
				{ id: 1211, nome: 'Literatura Comparada' },
				{ id: 1212, nome: 'Artes' },
				{ id: 1213, nome: 'Fundamentos e Crítica das Artes' },
				{ id: 1214, nome: 'Teoria da Arte' },
				{ id: 1215, nome: 'História da Arte' },
				{ id: 1216, nome: 'Crítica da Arte' },
				{ id: 1217, nome: 'Artes Plásticas' },
				{ id: 1218, nome: 'Pintura' },
				{ id: 1219, nome: 'Desenho' },
				{ id: 1220, nome: 'Gravura' },
				{ id: 1221, nome: 'Escultura' },
				{ id: 1222, nome: 'Cerâmica' },
				{ id: 1223, nome: 'Tecelagem' },
				{ id: 1224, nome: 'Música' },
				{ id: 1225, nome: 'Regência' },
				{ id: 1226, nome: 'Instrumentação Musical' },
				{ id: 1227, nome: 'Composição Musical' },
				{ id: 1228, nome: 'Canto' },
				{ id: 1229, nome: 'Dança' },
				{ id: 1230, nome: 'Execução da Dança' },
				{ id: 1231, nome: 'Coreografia' },
				{ id: 1232, nome: 'Teatro' },
				{ id: 1233, nome: 'Dramaturgia' },
				{ id: 1234, nome: 'Direção Teatral' },
				{ id: 1235, nome: 'Cenografia' },
				{ id: 1236, nome: 'Interpretação Teatral' },
				{ id: 1237, nome: 'Ópera' },
				{ id: 1238, nome: 'Fotografia' },
				{ id: 1239, nome: 'Cinema' },
				{ id: 1240, nome: 'Administração e Produção de Filmes' },
				{ id: 1241, nome: 'Roteiro e Direção Cinematográficos' },
				{ id: 1242, nome: 'Técnicas de Registro e Processamento de Filmes' },
				{ id: 1243, nome: 'Interpretação Cinematográfica' },
				{ id: 1244, nome: 'Artes do Vídeo' },
				{ id: 1245, nome: 'Educação Artística' },
            ],
        },

    ],
};
