apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceua-pvc
  namespace: ceua
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

