module.exports = {
	membros: [
		{
			id: 1,
			nome: 'Membro A',
			cpf: '...',
			email: 'membroA.ceua@ufpe.br',
			vinculo: '4',
			instituicao: '1',
			campus: '...',
			departamento: '...',
			lattes_url: 'https://lattes.com.br/jkfldjskflds',
			experiencia:  '1',
			experiencia_tempo: '+10 anos',
			treinamento: '1',
			treinamento_carga_horaria: '400 horas',
			treinamento_certificado_url: 'https://drive.google.com/view/jkfldsjfksdllfdls',
			observacoes: '',
		},
		{
			id: 2,
			nome: 'Membro B',
			cpf: '...',
			email: 'membroB.ceua@ufpe.br',
			vinculo: '4',
			instituicao: '1',
			campus: '...',
			departamento: '...',
			lattes_url: 'https://lattes.com.br/jkfldjskflds',
			experiencia:  '0',
			experiencia_tempo: '+2 anos',
			treinamento: '1',
			treinamento_carga_horaria: '360 horas',
			treinamento_certificado_url: 'https://drive.google.com/view/jkfldsjfksdllfdls',
			observacoes: '',
		},
		{
			id: 3,
			nome: 'Membro C',
			cpf: '...',
			email: 'membroC.ceua@ufpe.br',
			vinculo: '4',
			instituicao: '1',
			campus: '...',
			departamento: '...',
			lattes_url: 'https://lattes.com.br/jkfldjskflds',
			experiencia:  '1',
			experiencia_tempo: '+5 anos',
			treinamento: '1',
			treinamento_carga_horaria: '200 horas',
			treinamento_certificado_url: 'https://drive.google.com/view/jkfldsjfksdllfdls',
			observacoes: '',
		}
	],
};
